#!/bin/sh

# Regenerate ligand:receptor complex with rigid ligand 
#../../../bin/dock6 -i rigid.in

# Regenerate ligand:receptor complex with flex ligand
../../../bin/dock6 -i test_anchor_and_grow.in
