#!/bin/sh

# Generate the molecular surface of the receptor
# This, rec.ms, has already been generated using program dms.

# Construct sphere set in active site
../../../bin/sphgen

# Select spheres within 10 Ang of ligand 
../../../bin/sphere_selector rec.sph ../1_struct/lig.mol2 5.0

# Convert selected spheres into pdb format for viewing
../../../bin/showsphere < selected_spheres.in

# Convert spheres from largest cluster into pdb format for viewing
../../../bin/showsphere < sphgen_cluster.in
